#!/bin/bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  FuelSniffer Deployment Script${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Preflight Checks
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${YELLOW}Preflight checks...${NC}"

# Check Docker is installed
if ! command -v docker &> /dev/null; then
  echo -e "${RED}✗ Docker is not installed. Please install Docker first.${NC}"
  exit 1
fi

# Check Docker daemon is running
if ! docker info &> /dev/null; then
  echo -e "${RED}✗ Docker daemon is not running. Please start Docker.${NC}"
  exit 1
fi

echo -e "${GREEN}✓ Docker is installed and running${NC}"

# Check docker compose is available
if ! docker compose version &> /dev/null; then
  echo -e "${RED}✗ docker compose is not available. Please install Docker Compose.${NC}"
  exit 1
fi

echo -e "${GREEN}✓ docker compose is available${NC}"

# Check we're in the right directory
if [ ! -d "fuelsniffer" ]; then
  echo -e "${RED}✗ fuelsniffer/ directory not found. Run this script from the repo root.${NC}"
  exit 1
fi

if [ ! -f "fuelsniffer/docker-compose.yml" ]; then
  echo -e "${RED}✗ docker-compose.yml not found in fuelsniffer/. Check the repo structure.${NC}"
  exit 1
fi

echo -e "${GREEN}✓ Project structure is valid${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Environment Variables
# ─────────────────────────────────────────────────────────────────────────────

ENV_FILE="fuelsniffer/.env"
OVERRIDE_FILE="fuelsniffer/docker-compose.override.yml"

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}Found existing .env file.${NC}"
  read -p "Do you want to reconfigure it? (y/n) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}Using existing .env...${NC}"
    USE_EXISTING_ENV=true
  else
    USE_EXISTING_ENV=false
  fi
else
  USE_EXISTING_ENV=false
fi

if [ "$USE_EXISTING_ENV" != "true" ]; then
  echo ""
  echo -e "${BLUE}Setting up environment variables...${NC}"
  echo ""

  # DB_PASSWORD
  echo "Database password (for PostgreSQL fuelsniffer user):"
  read -sp "Enter DB_PASSWORD (leave blank to auto-generate): " DB_PASSWORD
  echo
  if [ -z "$DB_PASSWORD" ]; then
    DB_PASSWORD=$(openssl rand -base64 16 | tr -d '=+/' | cut -c1-16)
    echo -e "${GREEN}Generated: ${DB_PASSWORD}${NC}"
  fi

  # QLD_API_TOKEN
  echo ""
  echo "Queensland Fuel Price API token (required):"
  echo "Register at https://www.fuelpricesqld.com.au as a data consumer"
  read -p "Enter QLD_API_TOKEN: " QLD_API_TOKEN
  while [ -z "$QLD_API_TOKEN" ]; do
    echo -e "${RED}QLD_API_TOKEN is required${NC}"
    read -p "Enter QLD_API_TOKEN: " QLD_API_TOKEN
  done

  # SESSION_SECRET
  echo ""
  echo "Session secret (for JWT signing, 32+ chars):"
  read -sp "Enter SESSION_SECRET (leave blank to auto-generate): " SESSION_SECRET
  echo
  if [ -z "$SESSION_SECRET" ]; then
    SESSION_SECRET=$(openssl rand -base64 32)
    echo -e "${GREEN}Generated: (hidden)${NC}"
  fi

  # HEALTHCHECKS_PING_URL
  echo ""
  echo "Healthchecks.io ping URL (optional, for scraper health monitoring):"
  read -p "Enter HEALTHCHECKS_PING_URL (leave blank to skip): " HEALTHCHECKS_PING_URL

  # DATABASE_URL
  DATABASE_URL="postgresql://fuelsniffer:${DB_PASSWORD}@postgres:5432/fuelsniffer"

  # Write .env
  cat > "$ENV_FILE" << EOF
# FuelSniffer Environment
# Generated by deploy.sh on $(date)

# Database
DB_PASSWORD=${DB_PASSWORD}

# QLD Fuel Price API — register at https://www.fuelpricesqld.com.au
QLD_API_TOKEN=${QLD_API_TOKEN}

# healthchecks.io dead-man's-switch (optional)
HEALTHCHECKS_PING_URL=${HEALTHCHECKS_PING_URL}

# Database connection
DATABASE_URL=${DATABASE_URL}

# Session secret for JWT signing
SESSION_SECRET=${SESSION_SECRET}
EOF

  chmod 600 "$ENV_FILE"
  echo -e "${GREEN}✓ .env written${NC}"
fi

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Cloudflare Configuration
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${BLUE}Cloudflare Tunnel Configuration${NC}"
echo ""
echo "The app can optionally be exposed via Cloudflare Tunnel (no port forwarding needed)."
echo "For now, you can run the app locally and skip this."
echo ""

read -p "Do you want to configure Cloudflare Tunnel? (y/n) " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo ""
  echo "To set up a Cloudflare Tunnel:"
  echo "1. Go to https://one.dash.cloudflare.com → Zero Trust → Tunnels"
  echo "2. Create a new tunnel and get the token"
  echo ""
  read -p "Enter your Cloudflare tunnel token: " TUNNEL_TOKEN

  if [ -n "$TUNNEL_TOKEN" ]; then
    cat > "$OVERRIDE_FILE" << EOF
services:
  cloudflared:
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
EOF
    chmod 644 "$OVERRIDE_FILE"
    echo -e "${GREEN}✓ Cloudflare tunnel configured${NC}"
  else
    echo -e "${YELLOW}Skipping Cloudflare tunnel setup${NC}"
    rm -f "$OVERRIDE_FILE"
  fi
else
  # Disable cloudflared service
  cat > "$OVERRIDE_FILE" << EOF
services:
  cloudflared:
    profiles:
      - disabled
EOF
  chmod 644 "$OVERRIDE_FILE"
  echo -e "${BLUE}Cloudflared service disabled (local deployment only)${NC}"
fi

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Build and Launch
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${BLUE}Building and launching services...${NC}"
echo ""

cd fuelsniffer

echo -e "${YELLOW}Running: docker compose build${NC}"
if ! docker compose build; then
  echo -e "${RED}✗ Build failed. Last 20 lines of output:${NC}"
  docker compose build 2>&1 | tail -20
  exit 1
fi

echo ""
echo -e "${YELLOW}Running: docker compose up -d${NC}"
if ! docker compose up -d; then
  echo -e "${RED}✗ Failed to start services. Last 20 lines of output:${NC}"
  docker compose logs --tail=20
  exit 1
fi

echo -e "${GREEN}✓ Services started${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Health Check
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${BLUE}Waiting for app to be ready...${NC}"

HEALTH_CHECK_URL="http://localhost:3000/api/health"
MAX_RETRIES=60
RETRY_INTERVAL=5
RETRY_COUNT=0

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
  if curl -s "$HEALTH_CHECK_URL" > /dev/null 2>&1; then
    HEALTH=$(curl -s "$HEALTH_CHECK_URL")
    echo -e "${GREEN}✓ App is healthy${NC}"
    echo -e "${BLUE}Health status:${NC}"
    echo "$HEALTH" | jq . 2>/dev/null || echo "$HEALTH"
    break
  fi

  RETRY_COUNT=$((RETRY_COUNT + 1))
  if [ $((RETRY_COUNT % 6)) -eq 0 ]; then
    echo "  Waiting... ($((RETRY_COUNT * RETRY_INTERVAL))s elapsed)"
  fi
  sleep $RETRY_INTERVAL
done

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
  echo -e "${RED}✗ App failed to become healthy after ${MAX_RETRIES} retries${NC}"
  echo ""
  echo -e "${YELLOW}Check logs:${NC}"
  echo "  docker compose logs app --tail=50"
  exit 1
fi

echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Success
# ─────────────────────────────────────────────────────────────────────────────

echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  FuelSniffer is ready!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BLUE}Access the app:${NC}"
echo "  http://localhost:3000"
echo ""
echo -e "${BLUE}Useful commands:${NC}"
echo "  View logs:        docker compose logs -f app"
echo "  View all services: docker compose ps"
echo "  Stop services:    docker compose down"
echo "  View database:    docker compose exec postgres psql -U fuelsniffer -d fuelsniffer"
echo ""
echo -e "${BLUE}Scraper:${NC}"
echo "  Runs every 15 minutes automatically"
echo "  Check /api/health for last run status"
echo ""
